In [1]:
import numpy as np  #1 Import the numpy package under the name np

In [2]:
np.zeros(10) #2 Create a null vector of size 10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a = np.arange(10, 49) #3 Create a vector with values ranging from 10 to 49
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [5]:
a.shape #4 Find the shape of previous array in question 3

(39,)

In [55]:
print(a.dtype) #5 Print the type of the previous array in question 3

int32


In [10]:
print(np.__version__)  #6 Print the numpy version and the configuration
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
None


In [56]:
print(a.ndim)  #7 Print the dimension of the array in question 3

1


In [18]:
np.ones((2,2), dtype=bool)  #8 Create a boolean array with all the True values

array([[ True,  True],
       [ True,  True]])

In [22]:
np.arange(10).reshape(2,5)  #9 Create a two dimensional array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.arange(20).reshape(2,5,2)  #10 Create a three dimensional array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [39]:
x = np.arange(20)  #11 Reverse a vector (first element becomes las
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
x = x[::-1]
x

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [41]:
x = np.zeros(10)  #12 Create a null vector of size 10 but the fifth value which is 1
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [46]:
np.identity(3)  #13 Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr = np.array([1, 2, 3, 4, 5])  #14 Convert the data type of the given array from int to float
arr1 = np.array([1, 2, 3, 4, 5], dtype=float)  #Method 1
arr2 = arr.astype('float')  #Method 2
arr1, arr2

(array([1., 2., 3., 4., 5.]), array([1., 2., 3., 4., 5.]))

In [59]:
arr1 = np.array([[1., 2., 3.],  #15 Multiply arr1 with arr2
            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [67]:
arr1 == arr2  #16 Make an array by comparing both the arrays provided above

array([[False, False, False],
       [False, False, False]])

In [82]:
arr = np.arange(10)  #17 Extract all odd numbers from arr with values(0-9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
odd = arr[arr % 2 == 1]
odd

array([1, 3, 5, 7, 9])

In [85]:
odd[:] = -1  # 18 Replace all odd numbers to -1 from previous array
arr[arr % 2 == 1] = -1  # Replace all odd numbers to -1 from main array
odd, arr

(array([-1, -1, -1, -1, -1]), array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]))

In [86]:
arr = np.arange(10)  #19 Replace the values of indexes 5,6,7 and 8 to 12
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr[5:9] = 12 
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [109]:
x = np.ones((6,6), dtype='int') #20 Create a 2d array with 1 on the border and 0 inside
x

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [105]:
x[1:-1,1:-1] = 0 
x

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

In [110]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  #21 Replace the value 5 to 12
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr2d[arr2d == 5] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [117]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d  #22 Convert all the values of 1st array to 64

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [119]:
arr3d[:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[64, 64, 64],
        [64, 64, 64]]])

In [139]:
arr2d = np.arange(10).reshape(2,5)  #23 Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr2d


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [122]:
arr2d[0]

array([0, 1, 2, 3, 4])

In [127]:
arr2d[1,1]  #24 Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

6

In [151]:
x = arr2d[0:3,2:3]  #25 Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
x

array([[2],
       [7]])

In [156]:
x = np.random.randn(10,10)  #26 Create a 10x10 array with random values and find the minimum and maximum values
x

array([[ 1.35251953,  0.94937698, -0.89277477, -0.53869575, -0.41588125,
         0.3373294 , -0.31492275,  0.32581487, -0.40644878, -0.10386892],
       [ 0.66418167, -1.57180257,  0.44088466, -1.26620589,  1.21678675,
         0.42573961, -0.73465335, -0.18893746,  1.61840147, -1.58201283],
       [-0.1916014 ,  0.10970398, -0.50800138, -0.35942638, -1.00786093,
        -1.01010341,  0.67824314,  0.397634  ,  0.85927432, -1.32205276],
       [ 0.00963672, -0.57972701,  1.6928537 ,  0.08288353, -1.36693458,
        -0.01172066,  0.08309548,  0.70698181,  0.11579004, -0.69300296],
       [-1.64044258, -1.88384985, -0.40460915,  1.12658245, -0.74823156,
        -1.26103528, -0.37562957, -1.5427501 ,  1.70980425, -1.14906537],
       [-0.87835861, -0.30622472, -0.95244941, -1.0808049 ,  0.3038965 ,
        -0.98392447, -1.01335068,  1.08016436, -1.27601176, -0.77605685],
       [-0.47484798,  0.3346545 , -2.05859167,  0.64278089,  0.12795534,
        -0.82864644,  0.54918838,  1.05443766

In [159]:
x.min(), x.max()

(-2.824989404732824, 1.709804254515624)

In [160]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a, b

(array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]),
 array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8]))

In [165]:
np.intersect1d(a, b)  #27 Find the common items between a and b

array([2, 4])

In [169]:
np.where(a == b), np.where(np.in1d(a, b))   #28 Find the positions where elements of a and b match

((array([1, 3, 5, 7], dtype=int64),), (array([1, 3, 5, 7], dtype=int64),))

In [173]:
#29 Find all the values from array data where the values from array names are not equal to Will
#30 Find all the values from array data where the values from array names are not equal to Will and Joe

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data, names

(array([[ 0.82378485,  0.93059656,  2.45152427,  0.63038466],
        [ 1.5620274 ,  1.58154037,  0.91255366, -0.39847832],
        [-0.41428785, -0.21510838,  0.84008646, -0.76989227],
        [ 1.28644178,  0.22376849,  1.77906215, -1.68946845],
        [-0.83321228,  1.19872694, -0.2139623 ,  0.38772258],
        [ 0.13732077, -0.0314896 , -0.84745336, -0.4931908 ],
        [-0.61127512,  0.20653756,  0.20734152, -1.078156  ]]),
 array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4'))

In [204]:
data[np.where(names != "Will")]

array([[ 0.82378485,  0.93059656,  2.45152427,  0.63038466],
       [ 1.5620274 ,  1.58154037,  0.91255366, -0.39847832],
       [ 1.28644178,  0.22376849,  1.77906215, -1.68946845],
       [ 0.13732077, -0.0314896 , -0.84745336, -0.4931908 ],
       [-0.61127512,  0.20653756,  0.20734152, -1.078156  ]])

In [205]:
data[np.where((names != "Will") & (names != "Joe"))]

array([[ 0.82378485,  0.93059656,  2.45152427,  0.63038466],
       [ 1.28644178,  0.22376849,  1.77906215, -1.68946845]])

In [229]:
#31 Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

np.random.uniform(2,15, size=(5,3))

array([[13.2535681 ,  4.07360883, 13.48634215],
       [ 9.85708279,  2.68181713,  3.23311936],
       [ 4.84337224,  3.32214863,  5.29712459],
       [12.02636388,  5.07001013, 14.97205813],
       [ 7.81235396,  7.94166419,  4.57695593]])

In [232]:
#32 Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

x = np.random.uniform(2,16, size=(2,2,4))
x

array([[[ 5.08563463, 13.30814899, 14.80571646, 12.51657602],
        [ 6.07808595, 11.43473194,  2.15187656, 14.60904445]],

       [[ 6.97875553, 15.84682102, 15.53304205,  4.00557311],
        [ 5.5388323 , 15.82548449,  3.57750497, 15.44146353]]])

In [250]:
#33 Swap axes of the array you created in Question 32

x.T, x.transpose() # both should be right

(array([[[ 5.08563463,  6.97875553],
         [ 6.07808595,  5.5388323 ]],
 
        [[13.30814899, 15.84682102],
         [11.43473194, 15.82548449]],
 
        [[14.80571646, 15.53304205],
         [ 2.15187656,  3.57750497]],
 
        [[12.51657602,  4.00557311],
         [14.60904445, 15.44146353]]]),
 array([[[ 5.08563463,  6.97875553],
         [ 6.07808595,  5.5388323 ]],
 
        [[13.30814899, 15.84682102],
         [11.43473194, 15.82548449]],
 
        [[14.80571646, 15.53304205],
         [ 2.15187656,  3.57750497]],
 
        [[12.51657602,  4.00557311],
         [14.60904445, 15.44146353]]]))

In [254]:
#34 Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

x = np.arange(10)
x, x.size

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 10)

In [279]:
y = np.sqrt(x)
y

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [287]:
y[np.where(y< 0.5)] = 0
y.astype(np.int), y

(array([0, 1, 1, 1, 2, 2, 2, 2, 2, 3]),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]))

In [304]:
#35 Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

x = np.random.randn(12)
y = np.random.randn(12)
x, y, x.max(), y.max(), 

(array([-1.07620857,  2.23120172,  1.31877096, -0.40724867,  0.31348729,
        -0.22430239, -0.31002688,  0.48764521, -0.20337227,  1.85560243,
        -0.85129194, -1.7262047 ]),
 array([ 0.89489943, -1.10706111,  0.15644538, -0.06493679, -0.74000726,
        -2.06083471, -1.75123859, -0.15484344,  0.61020493, -1.09338617,
        -0.04589116, -1.12472365]),
 2.231201719468318,
 0.8948994340480497)

In [306]:
np.stack((x.max(), y.max()))

array([2.23120172, 0.89489943])

In [307]:
#36 Find the unique names and sort them out!

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [309]:
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [310]:
#37 From array a remove all items present in array b

a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a, b

(array([1, 2, 3, 4, 5]), array([5, 6, 7, 8, 9]))

In [311]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [314]:
#38 Following is the input NumPy array, delete column two and insert following new column in its place.

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [315]:
sampleArray = np.delete(sampleArray, 1, axis = 1)
sampleArray

array([[34, 73],
       [82, 12],
       [53, 66]])

In [316]:
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 1)
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [318]:
#39 Find the dot product of the above two matrix

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x, y

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 6., 23.],
        [-1.,  7.],
        [ 8.,  9.]]))

In [321]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [325]:
#40 Generate a matrix of 20 random values and find its cumulative sum

x = np.ndarray(20)
x

array([0.82378485, 0.93059656, 2.45152427, 0.63038466, 1.5620274 ,
       1.58154037, 0.91255366, 0.39847832, 1.28644178, 0.22376849,
       1.77906215, 1.68946845, 0.13732077, 0.0314896 , 0.84745336,
       0.4931908 , 0.61127512, 0.20653756, 0.20734152, 1.078156  ])

In [326]:
np.cumsum(x)

array([ 0.82378485,  1.75438142,  4.20590569,  4.83629035,  6.39831775,
        7.97985812,  8.89241178,  9.29089009, 10.57733187, 10.80110037,
       12.58016252, 14.26963097, 14.40695174, 14.43844134, 15.2858947 ,
       15.7790855 , 16.39036062, 16.59689819, 16.80423971, 17.88239571])