In [98]:
import numpy as np       #1
print(np.__version__)

1.19.2


In [9]:
np.arange(10) #2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.ones((3,3), dtype=bool) #3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
arr = np.arange(10) #4
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr.reshape(2,-1)  #4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
a = np.array([1,2,3])  #5
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])  #6
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [53]:
a = np.array([1,2,3,4,5])  #7
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])  #8
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [64]:
a = np.array([2, 6, 1, 9, 10, 3, 27])  #9
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [65]:
a = np.array([1,2,2,3,3,4,4,4,5,6,7,8,8,8])  #10
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
arr = np.arange(9).reshape(3,3)  #11
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
arr[:,[1, 0, 2]]  #12

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [68]:
arr = np.arange(9).reshape(3,3)  #13
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr[[1, 0, 2],]  #13

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [82]:
a = np.random.randn(2,3)  #14
a

array([[ 1.56005065,  0.37463669, -0.08807875],
       [-0.77031153,  0.41949936,  0.82939246]])

In [83]:
a.sum()  #15

2.3251888794575497

In [84]:
a.min()  #16

-0.7703115297178622

In [85]:
a.max()  #17

1.5600506531128002

In [86]:
a.mean()  #18

0.38753147990959164

In [88]:
a = np.arange(15).reshape(3,5)  #19
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
a.shape  #19

(3, 5)

In [90]:
a.size  #20

15

In [92]:
a.ndim  #21

2

In [94]:
a = np.arange(10)**2  #22
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [95]:
a[2]  #23

4

In [96]:
a[2:5]  #24

array([ 4,  9, 16], dtype=int32)

In [97]:
a < 36  #25

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [99]:
np.identity(4)  #26

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
x = np.arange(6).reshape(2,3)  #27
x

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
np.zeros_like(x) #27

array([[0, 0, 0],
       [0, 0, 0]])

In [104]:
y = np.arange(3, dtype=float)  #27
y

array([0., 1., 2.])

In [106]:
np.zeros_like(y)  #27

array([0., 0., 0.])

In [107]:
np.zeros(5)  #28

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros(5, dtype=int)  #28

array([0, 0, 0, 0, 0])

In [110]:
np.zeros((2, 1))  #29

array([[0.],
       [0.]])

In [112]:
a = np.array([1, 2, 3])  #30
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [113]:
a = np.array([[1], [2], [3]])  #31
b = np.array([[2], [3], [4]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [117]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])  #32
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [119]:
x[np.nonzero(x)]  #33

array([3, 4, 5, 6])

In [120]:
x = np.arange(9)  #34
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
np.split(x, 3)  #34

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [123]:
x = np.arange(8)  #35
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [126]:
np.array_split(x, 3)  #35

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [127]:
np.linspace(2.0, 3.0, num=5)  #36

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [132]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], 
           [30, 31, 32, 33]]                  #37
np.choose([2, 3, 1, 0], choices)

array([20, 31, 12,  3])

In [135]:
a = np.array([[1,2,3], [4,5,6]])  #38
a
np.cumsum(a, dtype=float)

array([ 1.,  3.,  6., 10., 15., 21.])

In [137]:
a = np.array([1, 2, 3])  #39
a
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [145]:
a = np.arange(24).reshape((2,3,4))  #40
b = np.arange(4)
a, b

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([0, 1, 2, 3]))

In [146]:
np.inner(a, b)  #40

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [149]:
a = [4, 3, 5, 7, 6, 8]  #41
indices = [0, 2, 5]
np.take(a, indices)

array([4, 5, 8])

In [150]:
x = np.arange(4).reshape(2,2)  #42
x

array([[0, 1],
       [2, 3]])

In [151]:
np.transpose(x)  #42

array([[0, 2],
       [1, 3]])

In [153]:
x = np.array([1, 2, 4, 7, 0])  #43
np.diff(x)

array([ 1,  2,  3, -7])

In [156]:
x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])  #44
np.diff(x)

array([[2, 3, 4],
       [5, 1, 2]])

In [157]:
np.diff(x, axis=0)  #45

array([[-1,  2,  0, -2]])

In [158]:
a = np.arange(3)  #46
a

array([0, 1, 2])

In [159]:
np.exp(a)  #46

array([1.        , 2.71828183, 7.3890561 ])

In [161]:
np.sqrt(a)  #47

array([0.        , 1.        , 1.41421356])

In [163]:
b = np.array([2., -1., 4.])  #48
np.add(a, b)

array([2., 0., 6.])

In [169]:
a = np.random.randn(3,4)  #49
a

array([[-0.32028855, -0.80233173,  1.1914354 , -0.43578761],
       [ 1.24743272,  1.72009531,  0.59379002,  1.05035958],
       [-1.14097517, -0.08659475, -0.38028375, -0.1101203 ]])

In [171]:
a.shape  #49

(3, 4)

In [175]:
b = a.ravel()  #50
b

array([-0.32028855, -0.80233173,  1.1914354 , -0.43578761,  1.24743272,
        1.72009531,  0.59379002,  1.05035958, -1.14097517, -0.08659475,
       -0.38028375, -0.1101203 ])

In [176]:
b.shape  #50

(12,)

In [178]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])  #51
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [179]:
np.rint(a)  #52

array([-2., -2., -0.,  0.,  2.,  2.,  2.])